version: '3'
services: 
  mongodb:
    image: mongo
    ports: 
      - 8989:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin 
      - MONGO_INITDB_ROOT_PASSWORD=passkeyforadmin
      
  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    ports:
      - 8988:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=passkeyforadmin
      - ME_CONFIG_MONGODB_SERVER=mongodb